Repository ito-org/ito-app, pull requests merged in 2020-04, with the labels that each got.

#35 [WIP] Mint-white Color Scheme
  App/components/ShieldIcon.tsx
  App/components/ShieldIcon2.tsx
  App/screens/Loading.tsx
  App/screens/Onboarding.tsx
  App/screens/OnboardingHow.tsx
Labels: enhancement

#36 Added types to navigation props
  App/App.tsx
  App/screens/ConfirmationCode.tsx
  App/screens/DataUpload.tsx
  App/screens/Endangerment.tsx
  App/screens/Home.tsx
  App/screens/HomeBluetooth.tsx
  App/screens/HomeTour1.tsx
  App/screens/HomeTour2.tsx
  App/screens/Loading.tsx
  App/screens/Onboarding.tsx
  App/screens/OnboardingHow.tsx
  App/screens/SymptomInfo.tsx
Labels: enhancement

#66 Add Header component that uses Logo
  App/App.tsx
  App/components/AlphaNotice.tsx
  App/components/BasicButton.tsx
  App/components/Header.tsx
  App/components/Logo.tsx
  App/components/NavigationButton.tsx
  App/components/ShieldIcon.tsx
  App/components/ShieldIcon2.tsx
  App/screens/AlphaPositiveResult.tsx
  App/screens/AlphaWarning.tsx
  App/screens/BluetoothNotification.tsx
  App/screens/ConfirmationCode.tsx
  App/screens/DataUpload.tsx
  App/screens/Endangerment.tsx
  App/screens/HomeBluetooth.tsx
  App/screens/HomeTour.tsx
  App/screens/Loading.tsx
  App/screens/Onboarding.tsx
  App/screens/OnboardingHow.tsx
  App/screens/SymptomInfo.tsx
  App/styles/index.tsx
  metro.config.ts
Labels: enhancement

#125 Close #122
  .github/workflows/android.yml
Labels: enhancement

#130 Splitting automations
  .github/workflows/android-feature.yml
  .github/workflows/android-master.yml
Labels: devops

#133 Run linting if and only if appropriate
  .github/workflows/eslint.yml
Labels: devops

#132 Add contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#129 Update NL translations with new EN strings
  assets/locales/nl.json
Labels: translations

#134 Clarify text of download link
  README.md
Labels: documentation

#141 fixed package.json after rename react-native-ito-bluetooth react-nati…
  package-lock.json
  package.json
Labels: dependencies, devops

#142 German translations by petgo3
  assets/locales/de.json
  assets/locales/en.json
  assets/locales/nl.json
  i18n.ts
Labels: translations

#151 Fix android pipeline
  .github/workflows/android-feature.yml
  .github/workflows/android.yml
  README.md
Labels: devops

#156 Added Dutch Translations for App
  assets/locales/nl.json
Labels: translations

#157 Update links to use new repo/pkg names
  App/screens/AlphaWarning.tsx
  README.md
Labels: documentation

#155 Add remaining translations for v2 and improve a few ones
  assets/locales/bn.json
  assets/locales/de.json
  assets/locales/en.json
  assets/locales/nl.json
  i18n.ts
Labels: translations

#167 Submit positive result using text field or scanner
  App/screens/PositiveResult.tsx
  package-lock.json
  package.json
Labels: bug
